name: new_ai_project
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  fl_chart: ^0.66.0
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.2
  cloud_firestore: ^5.6.6
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.0
  flutter_native_splash: ^2.2.19

# إعدادات أيقونات اللانشر
flutter_icons:
  android: true
  ios: true
  image_path: "images/logo.png"

# إعدادات شاشة الـ Splash
flutter_native_splash:
  color: "#ffffff"
  image: "images/logo.png"
  android: true
  ios: true

flutter:
  uses-material-design: true

  assets:
    - images/background.png
    - images/page_two_bg.png
    - images/login_page.png
    - images/forgot_password.png
    - images/reset_password.png
    - images/HOME_student.png
    - images/Home_doctor.png
    - images/Home_guardian.png
    - images/Works of year.png
    - images/Table_student.png
    - images/Table_student2.png
    - images/Attendance_Rate.png
    - images/Table_doctor.png
    - images/Attendance monitoring.png
    - images/Manual_Attendance.png
    - images/4401.jpg
    - images/4402.jpg
    - images/4405.jpg
    - images/4406.jpg
    - images/4408.jpg
    - images/4409.jpg
