// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyARHGUzRf3InWF6wfNI1hySnmN6fc7q92M',
    appId: '1:16059777411:web:ce22428618c31a845c36b6',
    messagingSenderId: '16059777411',
    projectId: 'attendance-tracker-e2e91',
    authDomain: 'attendance-tracker-e2e91.firebaseapp.com',
    storageBucket: 'attendance-tracker-e2e91.firebasestorage.app',
    measurementId: 'G-VG22J02T65',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAIfRY_n91Rrsh7hpOFGF_zbKar9q57sbc',
    appId: '1:16059777411:android:8e29abd95ebcf1d25c36b6',
    messagingSenderId: '16059777411',
    projectId: 'attendance-tracker-e2e91',
    storageBucket: 'attendance-tracker-e2e91.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDxp2subnK4pNkDDhF4eU0B78EL_iRXki0',
    appId: '1:16059777411:ios:ac074fa1868c5ad55c36b6',
    messagingSenderId: '16059777411',
    projectId: 'attendance-tracker-e2e91',
    storageBucket: 'attendance-tracker-e2e91.firebasestorage.app',
    iosBundleId: 'com.example.aiProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDxp2subnK4pNkDDhF4eU0B78EL_iRXki0',
    appId: '1:16059777411:ios:ac074fa1868c5ad55c36b6',
    messagingSenderId: '16059777411',
    projectId: 'attendance-tracker-e2e91',
    storageBucket: 'attendance-tracker-e2e91.firebasestorage.app',
    iosBundleId: 'com.example.aiProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyARHGUzRf3InWF6wfNI1hySnmN6fc7q92M',
    appId: '1:16059777411:web:4a4188e1c1c4fc9e5c36b6',
    messagingSenderId: '16059777411',
    projectId: 'attendance-tracker-e2e91',
    authDomain: 'attendance-tracker-e2e91.firebaseapp.com',
    storageBucket: 'attendance-tracker-e2e91.firebasestorage.app',
    measurementId: 'G-TQ5Q5E99LV',
  );
}
